# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 211d36e273ee6cfe0f18b389f1783e1b1f9c12326b98ea9fbf98ec2bcf0d93630cca8213c6da64e9f5bd99eaf2022a3f3c106ffc5b80236fe89bb94afc5c6b91

test:
  secret_key_base: 09374d84cb9c6029ee9cb7e22bd6bba3b9a38bb2ca7d4452f6fa3211910506585672682b9dd92fc9b2df19de27b4a989316e1997d8586f7d48f13a11b6ef970f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
